### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by RonRademaker** [ConnectHolland/MongoAggregations#18]
Make it possible to export the result of a an aggregation as CSV. Suggested API:

``` php
$result = $collection->aggregate($aggregationBuilder->build());
$csvBuilder = new CSVExport();
$csvBuilder->exportToFile($result, 'result.csv');
```

**Comment by gisoconnectholland** [comment]
There are lots of ways to convert an array to csv, maybe even in good separate libraries. I think this should not be implemented in the mongo aggregations library as it is not a logical part of this library.
Maybe a way to format the result array in a better way is required though.

**Comment by RonRademaker** [comment]
Thanks for the suggestion, I'll look into libraries to convert the array to CSV and only do the preprocessing in the library.

**Comment by RonRademaker** [comment]
I chose the phpleague CSV library for CSV generation.

**Comment by gisoconnectholland** [comment]
See the PR for a comment on this
